### ISSUE TITLE
Testnet: Q3 milestones

### ISSUE THREAD

**Issue by Tymmmy** [interledger/roadmap#34]
## Summary

Implement exchange currency in order for the user to send money from a currency to another currency.
Also if RapydSandbox only allows us USD, do some exchange magic.
Implement the verify email and forgotten password functionalities.
Introduce the auto-peering for testnet.

## Intended Outcomes

User can do the following:
- [x] Send funds from a currency to another currency - cross currency payment
- [x] Make sure all currencies work, not just USD
- [x] Forgotten password functionality
- [x] Verify email functionality when registering
- [x] General transactions list with some filters
- [x] Auto-peering functionality
- [ ] ~~Add Mojaloop Hub -> peering with rafiki.money (testnet)~~
